name: google_sign_in
description: Flutter plugin for Google Sign-In, a secure authentication system
  for signing in with a Google account on Android, iOS, macOS and web.
repository: https://github.com/flutter/packages/tree/main/packages/google_sign_in/google_sign_in
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+google_sign_in%22
version: 6.1.5

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: google_sign_in_android
      ios:
        default_package: google_sign_in_ios
      macos:
        default_package: google_sign_in_macos
      web:
        default_package: google_sign_in_web

dependencies:
  flutter:
    sdk: flutter
  google_sign_in_android: #^6.1.0
    git:
      url: https://github.com/miquido/packages
      path: packages/google_sign_in/google_sign_in_android
      ref: google_sign_in_macos
  google_sign_in_ios: #^5.5.0
    git:
      url: https://github.com/miquido/packages
      path: packages/google_sign_in/google_sign_in_ios
      ref: google_sign_in_macos
  google_sign_in_macos: #^5.6.3
    git:
      url: https://github.com/miquido/packages
      path: packages/google_sign_in/google_sign_in_macos
      ref: google_sign_in_macos
  google_sign_in_platform_interface: #^2.4.0
    git:
      url: https://github.com/miquido/packages
      path: packages/google_sign_in/google_sign_in_platform_interface
      ref: google_sign_in_macos
  google_sign_in_web: #^0.12.0
    git:
      url: https://github.com/miquido/packages
      path: packages/google_sign_in/google_sign_in_web
      ref: google_sign_in_macos

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  http: ">=0.13.0 <2.0.0"
  integration_test:
    sdk: flutter
  mockito: 5.4.1

topics:
  - authentication
  - google-sign-in

# The example deliberately includes limited-use secrets.
false_secrets:
  - /example/android/app/google-services.json
  - /example/ios/Runner/GoogleService-Info.plist
  - /example/ios/RunnerTests/GoogleSignInTests.m
